# Generated by Django 2.0.6 on 2018-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('search', models.TextField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('num', models.IntegerField()),
                ('pron', models.TextField(max_length=50)),
                ('type', models.TextField(max_length=20)),
            ],
        ),
    ]
